apiVersion: v1
kind: Service
metadata:
  name: computer-vision-service
spec:
  selector:
    app: computer-vision
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
